<a href="https://colab.research.google.com/github/25wh1a05f0-pixel/naascom/blob/main/Health_care_Case_study.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Patient Monitoring System Data Analysis

## Project Overview
A hospital is developing a smart patient-monitoring system, collecting data on Heart Rate (BPM), Body Temperature (°C), Blood Oxygen Level (SpO₂ %), Systolic Blood Pressure (mmHg), and Patient Health Score (%). The goal is to classify a patient's condition as Normal, Requires Monitoring, or Critical.

This notebook will guide through the process of analyzing this patient data using Python, NumPy, Linear Algebra, and Calculus.

## Analysis Plan
1.  **Data Loading**: Load the patient monitoring data into a pandas DataFrame.
2.  **Data Preprocessing**: Clean the data, handle missing values, convert data types, and prepare it for analysis.
3.  **Exploratory Data Analysis (EDA)**: Understand the data distribution, relationships between variables, and identify potential patterns or anomalies. This will involve visualizations and statistical summaries.
4.  **Feature Engineering**: Create new features from existing ones if necessary to improve model performance.
5.  **Condition Classification**: Develop a model (e.g., using machine learning) to classify patient conditions into 'Normal', 'Requires Monitoring', or 'Critical' based on the physiological parameters.
6.  **Model Evaluation**: Assess the performance of the classification model.

---

## 1. Data Loading

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Please provide the data. Once the data is provided (e.g., as a CSV file), I can load it into a DataFrame. For example, if the data is in `patient_data.csv`:

In [5]:
# Patient monitoring data provided by the user
data = {
    'Time (h)': [0, 1, 2, 3, 4, 5],
    'Heart Rate (BPM)': [76, 82, 90, 98, 105, 112],
    'Body Temperature (°C)': [36.7, 37.0, 37.4, 38.0, 38.5, 39.0],
    'Blood Oxygen Level (SpO₂ %)': [98, 97, 96, 94, 92, 89],
    'Systolic Blood Pressure (mmHg)': [122, 125, 130, 135, 140, 148],
    'Patient Health Score (%)': [92, 88, 82, 74, 65, 52]
}

df = pd.DataFrame(data)
display(df.head())

,Time (h),Heart Rate (BPM),Body Temperature (°C),Blood Oxygen Level (SpO₂ %),Systolic Blood Pressure (mmHg),Patient Health Score (%)
0,0,76,36.7,98,122,92
1,1,82,37.0,97,125,88
2,2,90,37.4,96,130,82
3,3,98,38.0,94,135,74
4,4,105,38.5,92,140,65


## Task 1 — Analysis Using Python Basics

### 1. Display the Patient Readings
Using a for loop to display all patient readings.

In [6]:
print("Patient Readings:")
for index, row in df.iterrows():
    print(f"Time: {row['Time (h)']}h, Heart Rate: {row['Heart Rate (BPM)']} BPM, Temperature: {row['Body Temperature (°C)']}°C, SpO₂: {row['Blood Oxygen Level (SpO₂ %)']}%, Systolic BP: {row['Systolic Blood Pressure (mmHg)']} mmHg, Health Score: {row['Patient Health Score (%)']}%")

Patient Readings:
Time: 0.0h, Heart Rate: 76.0 BPM, Temperature: 36.7°C, SpO₂: 98.0%, Systolic BP: 122.0 mmHg, Health Score: 92.0%
Time: 1.0h, Heart Rate: 82.0 BPM, Temperature: 37.0°C, SpO₂: 97.0%, Systolic BP: 125.0 mmHg, Health Score: 88.0%
Time: 2.0h, Heart Rate: 90.0 BPM, Temperature: 37.4°C, SpO₂: 96.0%, Systolic BP: 130.0 mmHg, Health Score: 82.0%
Time: 3.0h, Heart Rate: 98.0 BPM, Temperature: 38.0°C, SpO₂: 94.0%, Systolic BP: 135.0 mmHg, Health Score: 74.0%
Time: 4.0h, Heart Rate: 105.0 BPM, Temperature: 38.5°C, SpO₂: 92.0%, Systolic BP: 140.0 mmHg, Health Score: 65.0%
Time: 5.0h, Heart Rate: 112.0 BPM, Temperature: 39.0°C, SpO₂: 89.0%, Systolic BP: 148.0 mmHg, Health Score: 52.0%


### 2. Identify High Temperature
If Temperature > 38°C, display “High Temperature Alert”. Otherwise, display “Temperature Normal”.

In [7]:
print("\nTemperature Status:")
for index, row in df.iterrows():
    if row['Body Temperature (°C)'] > 38:
        print(f"Time {row['Time (h)']}h: High Temperature Alert ({row['Body Temperature (°C)']}°C)")
    else:
        print(f"Time {row['Time (h)']}h: Temperature Normal ({row['Body Temperature (°C)']}°C)")


Temperature Status:
Time 0.0h: Temperature Normal (36.7°C)
Time 1.0h: Temperature Normal (37.0°C)
Time 2.0h: Temperature Normal (37.4°C)
Time 3.0h: Temperature Normal (38.0°C)
Time 4.0h: High Temperature Alert (38.5°C)
Time 5.0h: High Temperature Alert (39.0°C)


### 3. Identify Low Oxygen Level
If SpO₂ < 90%, display “Low Oxygen Alert”. Otherwise, display “Oxygen Level Normal”.

In [8]:
print("\nOxygen Level Status:")
for index, row in df.iterrows():
    if row['Blood Oxygen Level (SpO₂ %)'] < 90:
        print(f"Time {row['Time (h)']}h: Low Oxygen Alert ({row['Blood Oxygen Level (SpO₂ %)']}%) ")
    else:
        print(f"Time {row['Time (h)']}h: Oxygen Level Normal ({row['Blood Oxygen Level (SpO₂ %)']}%) ")


Oxygen Level Status:
Time 0.0h: Oxygen Level Normal (98.0%) 
Time 1.0h: Oxygen Level Normal (97.0%) 
Time 2.0h: Oxygen Level Normal (96.0%) 
Time 3.0h: Oxygen Level Normal (94.0%) 
Time 4.0h: Oxygen Level Normal (92.0%) 
Time 5.0h: Low Oxygen Alert (89.0%) 


### 4. Create a Function
Create `health_status(score)` that returns: Healthy (score > 80), Monitor (50 ≤ score ≤ 80), Critical (score < 50).

In [9]:
def health_status(score):
    if score > 80:
        return "Healthy"
    elif 50 <= score <= 80:
        return "Monitor"
    else:
        return "Critical"

print("\nPatient Health Status:")
for index, row in df.iterrows():
    status = health_status(row['Patient Health Score (%)'])
    print(f"Time {row['Time (h)']}h: Health Score {row['Patient Health Score (%)']}% -> Status: {status}")


Patient Health Status:
Time 0.0h: Health Score 92.0% -> Status: Healthy
Time 1.0h: Health Score 88.0% -> Status: Healthy
Time 2.0h: Health Score 82.0% -> Status: Healthy
Time 3.0h: Health Score 74.0% -> Status: Monitor
Time 4.0h: Health Score 65.0% -> Status: Monitor
Time 5.0h: Health Score 52.0% -> Status: Monitor


## Task 2 — Analysis Using NumPy

First, we convert the relevant patient monitoring data from the DataFrame into a NumPy array. The columns represent [Heart Rate, Temperature, SpO₂, Systolic BP, Health Score].

In [10]:
patient_data_np = df[['Heart Rate (BPM)', 'Body Temperature (°C)', 'Blood Oxygen Level (SpO₂ %)', 'Systolic Blood Pressure (mmHg)', 'Patient Health Score (%)']].to_numpy()
print("Patient Data as NumPy Array:")
print(patient_data_np)

Patient Data as NumPy Array:
[[ 76.   36.7  98.  122.   92. ]
 [ 82.   37.   97.  125.   88. ]
 [ 90.   37.4  96.  130.   82. ]
 [ 98.   38.   94.  135.   74. ]
 [105.   38.5  92.  140.   65. ]
 [112.   39.   89.  148.   52. ]]


### 1. Find the shape of the array and determine rows and columns.

In [11]:
array_shape = patient_data_np.shape
rows, cols = array_shape
print(f"Shape of the array: {array_shape}")
print(f"Number of rows: {rows}")
print(f"Number of columns: {cols}")

Shape of the array: (6, 5)
Number of rows: 6
Number of columns: 5


### 2. Calculate the average of each parameter.

In [12]:
average_params = np.mean(patient_data_np, axis=0)
parameter_names = ['Heart Rate (BPM)', 'Body Temperature (°C)', 'Blood Oxygen Level (SpO₂ %)', 'Systolic Blood Pressure (mmHg)', 'Patient Health Score (%)']
print("Average of each parameter:")
for i, avg in enumerate(average_params):
    print(f"{parameter_names[i]}: {avg:.2f}")

Average of each parameter:
Heart Rate (BPM): 93.83
Body Temperature (°C): 37.77
Blood Oxygen Level (SpO₂ %): 94.33
Systolic Blood Pressure (mmHg): 133.33
Patient Health Score (%): 75.50


### 3. Find maximum heart rate, minimum SpO₂, maximum temperature, maximum systolic BP, and minimum health score.

In [13]:
max_heart_rate = np.max(patient_data_np[:, 0])
min_spo2 = np.min(patient_data_np[:, 2])
max_temperature = np.max(patient_data_np[:, 1])
max_systolic_bp = np.max(patient_data_np[:, 3])
min_health_score = np.min(patient_data_np[:, 4])

print(f"Maximum Heart Rate: {max_heart_rate} BPM")
print(f"Minimum SpO₂: {min_spo2}%")
print(f"Maximum Temperature: {max_temperature}°C")
print(f"Maximum Systolic Blood Pressure: {max_systolic_bp} mmHg")
print(f"Minimum Health Score: {min_health_score}%")

Maximum Heart Rate: 112.0 BPM
Minimum SpO₂: 89.0%
Maximum Temperature: 39.0°C
Maximum Systolic Blood Pressure: 148.0 mmHg
Minimum Health Score: 52.0%


### 4. Extract the SpO₂ column as a NumPy vector.

In [14]:
spo2_vector = patient_data_np[:, 2]
print("SpO₂ column as a NumPy vector:")
print(spo2_vector)

SpO₂ column as a NumPy vector:
[98. 97. 96. 94. 92. 89.]


### 5. Find all rows satisfying Heart Rate > 100 BPM.

In [15]:
high_hr_rows = patient_data_np[patient_data_np[:, 0] > 100]
print("Rows with Heart Rate > 100 BPM:")
print(high_hr_rows)

Rows with Heart Rate > 100 BPM:
[[105.   38.5  92.  140.   65. ]
 [112.   39.   89.  148.   52. ]]


### 6. Find all rows satisfying SpO₂ < 90%.

In [16]:
low_spo2_rows = patient_data_np[patient_data_np[:, 2] < 90]
print("Rows with SpO₂ < 90%:")
print(low_spo2_rows)

Rows with SpO₂ < 90%:
[[112.  39.  89. 148.  52.]]


import numpy as np

# Final Analysis and Decision

# Patient Monitoring Dataset
data = np.array([
    [0,  76, 36.7, 98, 122, 92],
    [1,  82, 37.0, 97, 125, 88],
    [2,  90, 37.4, 96, 130, 82],
    [3,  98, 38.0, 94, 135, 74],
    [4, 105, 38.5, 92, 140, 65],
    [5, 112, 39.0, 89, 148, 52]
])

print("Patient Monitoring Dataset:")
print(data)

print("\nFinal Patient Analysis:")

for row in data:
    time, heart_rate, temp, spo2, bp, score = row

    if score >= 85:
        condition = "Normal"
    elif score >= 60:
        condition = "Requires Monitoring"
    else:
        condition = "Critical"

    print("Time:", int(time), "h ->", condition)

In [17]:
import numpy as np

# Patient Monitoring Dataset
data = np.array([
    [0, 76, 36.7, 98, 122, 92],
    [1, 82, 37.0, 97, 125, 88],
    [2, 90, 37.4, 96, 130, 82],
    [3, 98, 38.0, 94, 135, 74],
    [4, 105, 38.5, 92, 140, 65],
    [5, 112, 39.0, 89, 148, 52]
])

A = np.array([[2, 1],
              [1, 3]])

# Given X
X = np.array([[98],
              [38]])

# Calculate Y = AX
Y = A @ X

print("A =")
print(A)

print("\nX =")
print(X)

print("\nY = AX =")
print(Y)

# Matrix operations
print("\nTranspose of A:")
print(A.T)

print("\nDeterminant of A:")
print(np.linalg.det(A))

print("\nInverse of A:")
print(np.linalg.inv(A))

# Solve equations
B = np.array([100, 120])
solution = np.linalg.solve(A, B)

print("\nSolution of equations:")
print("x =", solution[0])
print("y =", solution[1])

A =
[[2 1]
 [1 3]]

X =
[[98]
 [38]]

Y = AX =
[[234]
 [212]]

Transpose of A:
[[2 1]
 [1 3]]

Determinant of A:
5.000000000000001

Inverse of A:
[[ 0.6 -0.2]
 [-0.2  0.4]]

Solution of equations:
x = 36.0
y = 28.0


Task 4 — Analysis Using Calculus
The patient's health score is modeled as H(t) = 100 − 4t − ½t², where H(t) is the health score and t is time in hours.
1. Differentiate H(t) and determine dH/dt.
2. Calculate dH/dt at t = 2 and t = 5.
3. Interpret whether the health score is decreasing at a constant, increasing, or decreasing rate.


In [18]:
import numpy as np
data = np.array([
    [0,  76, 36.7, 98, 122, 92],
    [1,  82, 37.0, 97, 125, 88],
    [2,  90, 37.4, 96, 130, 82],
    [3,  98, 38.0, 94, 135, 74],
    [4, 105, 38.5, 92, 140, 65],
    [5, 112, 39.0, 89, 148, 52]
])

print("Patient Monitoring Dataset:")
print(data)

Patient Monitoring Dataset:
[[  0.   76.   36.7  98.  122.   92. ]
 [  1.   82.   37.   97.  125.   88. ]
 [  2.   90.   37.4  96.  130.   82. ]
 [  3.   98.   38.   94.  135.   74. ]
 [  4.  105.   38.5  92.  140.   65. ]
 [  5.  112.   39.   89.  148.   52. ]]


import numpy as np

# Final Analysis and Decision

# Patient Monitoring Dataset
data = np.array([
    [0,  76, 36.7, 98, 122, 92],
    [1,  82, 37.0, 97, 125, 88],
    [2,  90, 37.4, 96, 130, 82],
    [3,  98, 38.0, 94, 135, 74],
    [4, 105, 38.5, 92, 140, 65],
    [5, 112, 39.0, 89, 148, 52]
])

print("Patient Monitoring Dataset:")
print(data)

print("\nFinal Patient Analysis:")

for row in data:
    time, heart_rate, temp, spo2, bp, score = row

    if score >= 85:
        condition = "Normal"
    elif score >= 60:
        condition = "Requires Monitoring"
    else:
        condition = "Critical"

    print("Time:", int(time), "h ->", condition)

In [19]:
import numpy as np

# Final Analysis and Decision


data = np.array([
    [0,  76, 36.7, 98, 122, 92],
    [1,  82, 37.0, 97, 125, 88],
    [2,  90, 37.4, 96, 130, 82],
    [3,  98, 38.0, 94, 135, 74],
    [4, 105, 38.5, 92, 140, 65],
    [5, 112, 39.0, 89, 148, 52]
])

print("Patient Monitoring Dataset:")
print(data)

print("\nFinal Patient Analysis:")

for row in data:
    time, heart_rate, temp, spo2, bp, score = row

    if score >= 85:
        condition = "Normal"
    elif score >= 60:
        condition = "Requires Monitoring"
    else:
        condition = "Critical"

    print("Time:", int(time), "h ->", condition)

Patient Monitoring Dataset:
[[  0.   76.   36.7  98.  122.   92. ]
 [  1.   82.   37.   97.  125.   88. ]
 [  2.   90.   37.4  96.  130.   82. ]
 [  3.   98.   38.   94.  135.   74. ]
 [  4.  105.   38.5  92.  140.   65. ]
 [  5.  112.   39.   89.  148.   52. ]]

Final Patient Analysis:
Time: 0 h -> Normal
Time: 1 h -> Normal
Time: 2 h -> Requires Monitoring
Time: 3 h -> Requires Monitoring
Time: 4 h -> Requires Monitoring
Time: 5 h -> Critical
